### ISSUE TITLE
Issue regarding bundler

### ISSUE THREAD

**Issue by villa9393** [ohza/3D_Scan_Project#12]
Hi,
May I know what do you mean by
"The path to Bundler needs to be adjusted in the local server installation"

For eg, my project is in c:/desktop/projectfolder
does that mean that the bundler program needs to be in the same folder?

**Comment by ohza** [comment]
Hi,

in the source-code for the server, there is a path to the bundler executable.
This path needs to be set to where your bundler installation is.

Look at file 3D_Scan_Server/src/ThreeD_ServerHandler.java
At line 50.

Kind regards,

Oswald

**Comment by villa9393** [comment]
Hi ohza thanks for your prompt reply.

I have downloaded and make the bundlersfm. But the files i have are bundle.exe, Bundle2Ply.exe, Bundle2PMVS.exe, Bundle2Vis.exe .
May i know which file should i use as the executable?
Many thanks

**Comment by villa9393** [comment]
Hi oswald, I have successfully set up the right path,
but i encounter another error as below

Performing Bundler2PMVS conversion...
Error opening file list.txt for reading
Error opening file pmvs/bundle.rd.out for reading
Num cameras: 0
Running Bundle2PMVS to generate geometry and converted camera file
Running RadialUndistort to undistort input images
Running Bundle2Vis to generate vis.dat
Traceback (most recent call last):
  File "RunPMVS.py", line 10, in <module>
    manager.doBundle2PMVS()
  File "c:\Users\villa\Desktop\osm-bundler\osm-bundlerWin64\osmpmvs\__init__.py", line 86, in doBundle2PMVS
    undistortTextFile = open("list.rd.txt", "r")
IOError: [Errno 2] No such file or directory: 'list.rd.txt'

Any idea how to solve it?

Many thanks in advance
